services:

  kafka:
    image: bitnamilegacy/kafka:latest  # FREE legacy version
    container_name: kafka
    restart: always

    ports:
      - "9092:9092"

    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "sensor_data:1:1"
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms256m"

    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: neha3002/scm-backend:latest
    container_name: scm_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


  producer:
    image: neha3002/scm-producer:latest
    container_name: kafka_producer
    depends_on:
      - kafka
    env_file:
      - .env
    restart: always

  consumer:
    image: neha3002/scm-consumer:latest
    container_name: kafka_consumer
    depends_on:
      - kafka
    env_file:
      - .env
    restart: always